export type {ITest} from "./src/TestInterface"
export type {IUserResponseDto} from "./src/dtoInterface/IUser.response.dto"
export type {ICreateUserRequestDto} from "./src/dtoInterface/ICreateUser.request.dto"
export type {IPatchUserRequestDto} from "./src/dtoInterface/IPatchUser.request.dto"
export type {ILoginUserRequestDto} from "./src/dtoInterface/ILoginUser.request.dto"
export type {IAuthUserResponseDto} from "./src/dtoInterface/IAuthUser.response.dto"
export type {ILogoutUserRequestDto} from "./src/dtoInterface/ILogoutUser.request.dto"
export type {ITimeLogDto} from "./src/dtoInterface/ITimeLog.dto"
export type {ITimeLogResponseDto} from "./src/dtoInterface/ITimeLog.response.dto"

export type {IServerToClientEvents} from "./src/socket/IServerToClientEvents"
export type {IClientToServerEvents} from "./src/socket/IClientToServerEvents"
export type {UserOnlineDto} from "./src/socket/UserOnlineDto"